# Voboost Configuration Demo
# This file demonstrates all available configuration options
# You can modify these values and see changes in real-time in the demo app

# Language settings: ru, en
settings-language: en

# Theme settings: light, dark
settings-theme: dark

# Interface positioning adjustments
settings-interface-shift-x: 0
settings-interface-shift-y: 0

# Fuel mode options: electric, hybrid, save
vehicle-fuel-mode: electric

# Drive mode options: eco, comfort, sport, snow, outing, individual
vehicle-drive-mode: individual
